import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import Instagram from "../components/Instagram";
import Slider from "../components/Slider";
import { Data } from "../components/Data";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Photography Next-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        heading="Capture Photography"
        message="I capture moments in nature and keep them alive."
        button="Home"
      />
      <Slider slides={Data} />
      <Instagram />
    </div>
  );
}
